# Description: The Linux kernel
# URL: http://www.kernel.org

name=linux
version=$LINUX_VERSION
release=1
depends=(native/linux-source)

build(){
   cd $NATIVE_SYSROOT/usr/src/linux

   make -j $JOBS ARCH=arm CROSS_COMPILE=$HOST-
   make -j $JOBS ARCH=arm CROSS_COMPILE=$HOST- modules
   make ARCH=arm CROSS_COMPILE=$HOST- INSTALL_MOD_PATH=$PKG modules_install

   # Cleanup
   rm $PKG/lib/modules/3.6.11/{build,source}

   cp arch/arm/boot/Image $OUTPUT/kernel.img
}
