# Description: A basic GNU/linux filesystem
# URL: http://www.buildgear.org

name=fs-qt4
version=1.0
release=1
depends=(core linux connman qt4)

build() {
   # Copy fully populated sysroot
   cp -a $SYSROOT/* $PKG

   # Set host name
   echo "raspberrypi" > $PKG/etc/hostname

   # Set login issue
   echo -e "Raspberry Pi Mini Qt4 Distribution $version\n" > $PKG/etc/issue

   # Cleanup
#   rm -rf $PKG/usr/include
   rm -rf $PKG/usr/lib/*.a
   rm -rf $PKG/usr/lib/*.la

   # Create tarball
   tar -C $PKG -acpf $OUTPUT/$name.tar.gz .
}
