# Description: The Raspberry Pi binaries
# URL: https://github.com/raspberrypi/firmware

name=bootloader
version=git-f715140
release=1

source=(https://github.com/raspberrypi/firmware/archive/${version/git-/}.zip)

build() {
   cd firmware-${version/git-/}*

   cp boot/start.elf $OUTPUT/start.elf
   cp boot/bootcode.bin $OUTPUT
}
