# Description: The Raspberry Pi binaries
# URL: https://github.com/raspberrypi/firmware

name=bootloader
version=git-baa3ecf
release=1
source=(https://github.com/raspberrypi/firmware/archive/${version/git-/}.zip
        config.txt cmdline.txt)

build() {
   cp $SRC/config.txt $OUTPUT
   cp $SRC/cmdline.txt $OUTPUT

   cd firmware-${version/git-/}*

   cp boot/start.elf $OUTPUT
   cp boot/bootcode.bin $OUTPUT
}
