# Description: A basic GNU/linux filesystem
# URL: http://www.buildgear.org

name=fs
version=1.0
release=1
depends=(core linux net-tools traceroute connman)

build() {
   # Copy fully populated sysroot
   cp -a $SYSROOT/* $PKG

   # Set host name
   echo "raspberrypi" > $PKG/etc/hostname

   # Set login issue
   echo -e "Raspberry Pi Mini Distribution $version\n" > $PKG/etc/issue

   # Force systemd to enable getty login on ttyAMA0 (auto detect fails)
   ln -s /usr/lib/systemd/system/serial-getty\@.service \
         $PKG/etc/systemd/system/getty.target.wants/serial-getty@ttyAMA0.service

   # Cleanup
   cd $PKG/usr/include; rm -rf !(python|python?.?)
   find $PKG/usr/lib -name '*.a'  -delete -o \
                     -name '*.la' -delete

   # Create tarball
   tar -C $PKG -acpf $OUTPUT/$name.tar.gz .
}
