# Description: The VideoCore libraries (hard float) for the Raspberry Pi
# URL: https://github.com/raspberrypi/firmware

name=vc
version=git-efef226
release=1

source=(http://buildgear.org/mirror/raspberrypi/vc-rbp-git-efef226.tar.xz)

build() {
   cd $name-rbp-$version

   install -d -m 744 $PKG/etc/ld.so.conf.d
   install -d -m 744 $PKG/usr{,/share/vc}
   install -d -m 744 $PKG/opt/vc
   cp -r {bin,include,lib,sbin} $PKG/usr
   cp -r {bin,include,lib,sbin} $PKG/opt/vc
   cp include/interface/vcos/pthreads/*.h $PKG/usr/include/interface/vcos
   cp LICENCE $PKG/usr/share/vc
   echo "/opt/vc/lib" > $PKG/etc/ld.so.conf.d/vc.conf
}
