# Description: A basic GNU/Linux filesystem with XBMC
# URL: http://www.buildgear.org

name=fs-xbmc
version=1.0
release=1
depends=(fs mesa-demos connman xbmc-rbp)

build() {
   # Copy fully populated sysroot
   cp -a $SYSROOT/* $PKG

   # Set host name
   echo "rbp-xbmc" > $PKG/etc/hostname

   # Set login issue
   echo -e "Raspberry Pi XBMC Distribution $version\n" > $PKG/etc/issue

   # Cleanup
   # rm -rf $PKG/usr/include
   rm -rf $PKG/usr/lib/*.a
   rm -rf $PKG/usr/lib/*.la

   # Create tarball
   tar -C $PKG -acpf $OUTPUT/$name.tar.gz .
}
