# Description: The Linux kernel for Raspberry Pi
# URL: https://github.com/raspberrypi/linux
# License: GPLv2

name=linux-source
version=git-c9f21f0
release=1
source=(https://github.com/raspberrypi/linux/archive/${version/git-/}.tar.gz
        raspberrypi.config)
options=(nostrip)

build(){
   mkdir -p $PKG/usr/src

   mv linux-${version/git-/}* $PKG/usr/src/linux
   cd $PKG/usr/src/linux

   cp $SRC/raspberrypi.config .config
}
